* cloud-sandbox:   - safer use of ubuntu-distro-info, from Scott Moser

diff --git a/cloud-sandbox b/cloud-sandbox
--- a/cloud-sandbox
+++ b/cloud-sandbox
@@ -84,7 +84,16 @@ release="$2"
 
 # Default to t1.micro/latest
 [ -z "$size" ] && size="t1.micro"
-[ -z "$release" ] && release="$(distro-info --devel || distro-info --all | tail -n 1) daily"
+if [ -z "$release" ]; then
+	command -v ubuntu-distro-info >/dev/null 2>&1 || { echo "FAIL: no ubuntu-distro-info."; exit 1; }
+	release=$(ubuntu-distro-info --devel 2>/dev/null)
+	if [ $? -ne 0 ]; then
+		echo "WARN: 'ubuntu-distro-info --devel' failed."
+		release=$(ubuntu-distro-info --all | tail -n 1) ||
+		{ echo "FAIL: failed to get latest distro"; exit 1; }
+	fi
+fi
+echo "release=$release"
 
 # Generate the user-data file, and a first set of keys
 d=$(mktemp -d /tmp/cloud.XXXXXXXXXX)
