renamed, cleaned up

diff --git a/cloud-tunnel b/cloud-tunnel
--- a/cloud-tunnel
+++ b/cloud-tunnel
@@ -1,7 +1,7 @@
 #!/bin/sh -e
 #
-#    webanonymous - anonymize web traffic by tunneling through
-#                   any EC2 instance, if you have one running
+#    cloud-tunnel - anonymize web traffic by encrypting and tunneling
+#                   traffic through a public cloud instance
 #
 #    Copyright (C) 2010 Dustin Kirkland <kirkland@ubuntu.com>
 #
@@ -26,13 +26,17 @@ SOCKS="10800"
 #SQUID="3128"
 #SSH_OPTS="-f -N -C -D $SOCKS -L $SQUID:localhost:$SQUID"
 SSH_OPTS="-f -N -C -D $SOCKS"
-PIDFILE="$HOME/.cache/$PROG.pid"
+
+error() {
+	echo "ERROR: $@" 1>&2
+	exit 1
+}
 
 case $1 in
 	start)	
 		instances=$(ec2-describe-instances | grep "^INSTANCE.*running")
 		hostname=$(echo "$instances" | awk '{print $4}')
-		keypair=$(echo "$instances" | awk '{print $7}')
+		[ -z "$hostname" ] && error "No running instances found -- try starting a cloud instance"
 		gconftool-2 -t string -s /system/proxy/mode "manual"
 		gconftool-2 -t string -s /system/proxy/socks_host "localhost"
 		gconftool-2 -t string -s /system/proxy/socks_port "$SOCKS"
@@ -44,16 +48,21 @@ case $1 in
 	stop)
 		gconftool-2 -t string -s /system/proxy/mode "off"
 #		gconftool-2 -t string -s /system/http_proxy/use_http_proxy "false"
+		# BUG: Ideally, we'd save the pid of the ssh process and kill that here
 		pkill -f "ssh $SSH_OPTS $USER@.*amazonaws.com"
 	;;
 	status)
 		if pgrep -f "ssh $SSH_OPTS $USER@.*amazonaws.com" >/dev/null; then
-			echo "Running"
+			echo "$PROG: running"
+			exit 0
 		else
-			echo "Not running"
+			echo "$PROG: not running"
+			exit 1
 		fi
 	;;
 	*)
-		exit 1
+		error "Unknown parameter"
 	;;
 esac
+
+exit 0
