Rewrite of purge-old-kernels
This is Bash script. This one purges requested amount of kernels OLDER than the current kernel, so it does not purge the newest kernel in  case system has not been rebooted after its installation. This one does not need superuser privileges, if you run it in simulate mode. This one has help option. Purges all "^linux-.*" packages corresponding the kernel versions.  Uses --auto-remove in apt-get command; maybe it is excessive?

diff --git a/purge-old-kernels b/purge-old-kernels
--- a/purge-old-kernels
+++ b/purge-old-kernels
@@ -1,58 +1,145 @@
-#!/bin/sh
+#!/bin/bash
 #
-#    purge-old-kernels - remove old kernel packages
-#    Copyright (C) 2012 Dustin Kirkland <kirkland@ubuntu.com>
+#  Copyright (C) 2015       Jarno Suni (8@iki.fi)
 #
-#    Authors: Dustin Kirkland <kirkland@ubuntu.com>
-#             Kees Cook <kees@ubuntu.com>
+#  This program is free software; you can redistribute it and/or modify
+#  it under the terms of the GNU General Public License as published by
+#  the Free Software Foundation; either version 2 of the License, or
+#  (at your option) any later version.
 #
-#    This program is free software: you can redistribute it and/or modify
-#    it under the terms of the GNU General Public License as published by
-#    the Free Software Foundation, version 3 of the License.
+#  This program is distributed in the hope that it will be useful,
+#  but WITHOUT ANY WARRANTY; without even the implied warranty of
+#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#  GNU General Public License for more details.
 #
-#    This program is distributed in the hope that it will be useful,
-#    but WITHOUT ANY WARRANTY; without even the implied warranty of
-#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#    GNU General Public License for more details.
+#  You should have received a copy of the GNU General Public License
+#  along with this program; if not, write to the Free Software
+#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 #
-#    You should have received a copy of the GNU General Public License
-#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-# Ensure we're running as root
-if [ "$(id -u)" != 0 ]; then
-	echo "ERROR: This script must run as root.  Hint..." 1>&2
-	echo "  sudo $0 $@" 1>&2
-	exit 1
-fi
+set -o nounset
+set -o errexit
 
-# NOTE: This script will ALWAYS keep the currently running kernel
-# NOTE: Default is to keep 2 more, user overrides with --keep N
-KEEP=2
-# NOTE: Any unrecognized option will be passed straight through to apt-get
-APT_OPTS=
-while [ ! -z "$1" ]; do
-	case "$1" in
-		--keep)
-			# User specified the number of kernels to keep
-			KEEP="$2"
-			shift 2
-		;;
-		*)
-			APT_OPTS="$APT_OPTS $1"
-			shift 1
-		;;
-	esac
+# Usage info
+show_help() {
+cat << EOF
+Usage: ${0##*/} [OPTION]...
+Purge some kernel related packages that have older version than the
+current kernel. This is especially useful in order to prevent /boot
+partition from getting full. First warn, if some linux-* packages are
+only partially or unsuccessfully installed.
+
+Options:
+    -h, -?, --help  Display this help and exit.
+    -k NUM,
+    --keep NUM,
+    --keep=NUM	    Keep NUM kernels that are older than the currently
+                    used one. Default is 1.
+    -s, --simulate  Dry-run; don't actually remove packages. You do not
+                    have to be superuser with this option.
+    -y, --yes       Purge without user confirmation.
+
+Exit Status:
+    Exit with 1, if some command line argument is invalid.
+    Inherit the exit status of the apt-get purge command issued.
+EOF
+}
+
+error()
+{
+   echo 'ERROR: '"$1" >&2
+   exit ${2:-1}
+}
+
+n=1
+yes=""
+simulate=""
+
+while :; do
+    case ${1-} in
+        -h|-\?|--help)
+            show_help
+            exit
+            ;;
+        -k|--keep)
+			if ! ${2:+false}; then
+              n=$2
+              shift 2
+              continue
+            else
+               error 'Must specify a non-empty "--keep NUM" argument.'
+            fi
+            ;;
+        --keep=?*)
+            n=${1#*=} # Delete everything up to "=" and assign the remainder.
+            ;;
+        --keep=)
+             error 'Must specify a non-empty "--keep NUM" argument.'
+            ;;
+		-s|--simulate)
+			simulate="-s"
+			;;
+        -y|--yes)
+			yes="-y"
+			;;
+        --)              # End of all options.
+            shift
+            break
+            ;;
+        -?*)
+            echo 'WARNING: Unknown option (ignored): '"$1" >&2
+            ;;
+        # Default case: If no more options then break out of the loop.
+        *)
+            break
+    esac
+
+    shift
 done
 
-# Build our list of kernel packages to purge
-CANDIDATES=$(ls -tr /boot/vmlinuz-* | head -n -${KEEP} | grep -v "$(uname -r)$" | cut -d- -f2- | awk '{print "linux-image-" $0 " linux-headers-" $0}' )
-for c in $CANDIDATES; do
-	dpkg-query -s "$c" >/dev/null 2>&1 && PURGE="$PURGE $c"
-done
-
-if [ -z "$PURGE" ]; then
-	echo "No kernels are eligible for removal"
-	exit 0
+if [ $# -ne 0 ] ; then
+ show_help
+ exit
 fi
 
-apt-get $APT_OPTS remove --purge $PURGE
+if ! [[ "$n" =~ ^[0-9]+$ ]] ; then
+ error "$n is invalid number of older kernels to keep."
+fi
+# $n is valid number
+
+Pkgs="$(dpkg-query --show --showformat='${Status} ${Package}\n' "linux-*" |
+ awk '$2!="ok" || ($3!="installed" && $3!="not-installed") {print $4}')"
+if [ "${Pkgs}" ]; then
+ echo -e "WARNING: The following linux packages are not properly\
+ installed. You may want to purge or reinstall them:\n"${Pkgs} >&2
+ if ! [[ "$simulate" || "$yes" ]]; then
+  read -r -p "Continue anyway (y/n)? " response
+  response=${response,,}    # tolower
+  ! [[ $response =~ ^(yes|y)$ ]] && exit
+ fi
+ echo
+fi
+
+# Versions of installed kernel packages
+Versions="$(dpkg-query --show --showformat='${Status} ${Package}\n' "linux-image-*" |
+sed -nr "s/^[^ ]+ ok installed .+image-([[:digit:].]+-[^-]+)-.+/\1/p" |
+sort --version-sort --unique)"
+
+#Alternative way, but maybe not as reliable, if kernel is only partially installed
+#Versions="$(ls -1U /boot/vmlinuz-* | cut -d- -f2,3 | sort -Vu)"
+
+# current kernel version number (present in the respective kernel
+# package name, too)
+current="$(uname -r | cut -f1,2 -d-)"
+
+# keep n versions that are older than the current one (if they exist).
+num=$(awk '($0==c){a=NR-1-n; if(a>0){print a}else{print 0} exit}' c=${current} n=$n <<<"${Versions}")
+VersionsToPurge="$(head -n ${num} <<<"${Versions}")"
+
+if [ "${VersionsToPurge}" ]; then
+	# purge linux packages matching the versions
+	apt-get -q ${simulate} ${yes} purge --auto-remove $(
+    sed -r -e 's/\./\\./g' -e 's/.*/^linux-.+-&($|-)/' <<<"$VersionsToPurge")
+else
+	echo "0 kernels purged."
+fi
