Update purge-old-kernels
Take into account dpkg selection states. Try to be compatible with linux-signed kernels and goldfish kernels.

diff --git a/purge-old-kernels b/purge-old-kernels
--- a/purge-old-kernels
+++ b/purge-old-kernels
@@ -19,6 +19,7 @@
 
 set -o nounset
 set -o errexit
+#set -o xtrace
 
 # Usage info
 show_help() {
@@ -26,8 +27,12 @@ cat << EOF
 Usage: ${0##*/} [OPTION]...
 Purge some kernel related packages that have older version than the
 current kernel. This is especially useful in order to prevent /boot
-partition from getting full. First warn, if some linux-* packages are
-only partially or unsuccessfully installed.
+partition from getting full. Also purge the kernel packages of certain
+version, if the installed key linux-image packages are marked for
+removal by dpkg --set-selections.
+
+First warn, if some linux-* packages are only partially or
+unsuccessfully installed, and let user choose, if to continue or not.
 
 Options:
     -h, -?, --help  Display this help and exit.
@@ -37,15 +42,18 @@ Options:
                     used one. Default is 1. More older kernels may be
                     kept, if they have such reverse dependencies
                     installed that are required for getting kernel
-                    updates, or if there are more than one type of
-                    kernels installed with same version number.
-    -s, --simulate  Dry-run; do not actually remove packages. You do not
+                    updates. Also, if a key linux-image package is
+                    marked "hold" by e.g. apt-mark, kernels with the
+                    respective version are not removed.
+    -s, --simulate  Dry-run; don't actually remove packages. You do not
                     have to be superuser with this option.
     -y, --yes       Purge without user confirmation.
 
 Exit Status:
     Exit with 1, if some command line argument is invalid.
-    Inherit the exit status of the apt-get purge command issued.
+    Exit with 2, if current kernel is not installed or is marked for
+    removal. Otherwise inherit the exit status of the apt-get purge
+    command issued.
 EOF
 }
 
@@ -101,22 +109,25 @@ while :; do
     shift
 done
 
-if [ $# -ne 0 ] ; then
+if [ $# -ne 0 ]; then
  show_help
  exit
 fi
 
-if ! [[ "$n" =~ ^[0-9]+$ ]] ; then
- error "$n is invalid number of older kernels to keep."
-fi
+! [[ "$n" =~ ^[0-9]+$ ]] && error "$n is invalid number of older kernels to keep." 1
 # $n is valid number
 
-Pkgs="$(dpkg-query --show --showformat='${Status} ${Package}\n' "linux-*" |
+! dpkg-query -W -f='${Status}\n' "linux-image-$(uname -r)" |
+ grep -qE "^(install|hold) ok installed" &&
+error "Current kernel is not successfully installed or it is marked for removal." 2
+# current kernel is successfully installed and wanted so
+
+Pkgs="$(dpkg-query -W -f='${Status} ${Package}\n' "linux-*" |
  awk '$2!="ok" || ($3!="installed" && $3!="not-installed") {print $4}')"
 if [ "${Pkgs}" ]; then
  echo -e "WARNING: The following linux packages are not properly\
- installed. You may want to purge or reinstall them:\n"${Pkgs} >&2
- if ! [[ "$simulate" || "$yes" ]]; then
+ installed. You may want to purge or reinstall them manually:\n"${Pkgs} >&2
+ if ! [ "$yes" ]; then
   read -r -p "Continue anyway (y/n)? " response
   response=${response,,}    # tolower
   ! [[ $response =~ ^(yes|y)$ ]] && exit
@@ -124,33 +135,65 @@ if [ "${Pkgs}" ]; then
  echo
 fi
 
-# Versions of installed kernel packages
-Versions="$(dpkg-query --show --showformat='${Status} ${Package}\n' "linux-image-*" |
-sed -nr "s/^[^ ]+ ok installed .+image-([[:digit:].]+-[^-]+)-.+/\1/p" |
-sort --version-sort --unique)"
+# Versions of installed kernel packages to decide, if remove or not
+Versions="$(dpkg-query -W -f='${Status} ${Package}\n' |
+sed -nr "s/^(install|hold) ok installed linux-image-([0-9.]+-[^-]+)-.+/\2/p" |
+sort -Vu)"
 
-#Alternative way, but maybe not as reliable, if kernel is only partially installed
-#Versions="$(ls -1U /boot/vmlinuz-* | cut -d- -f2,3 | sort -Vu)"
+# Versions of installed kernel packages marked for removal
+CandidateVersionsToPurge="$(dpkg-query -W -f='${Status} ${Package}\n' |
+sed -nr "s/^(deinstall|purge) ok installed linux-image-([0-9.]+-[^-]+)-.+/\2/p" |
+sort -Vu)"
 
-# current kernel version number (present in the respective kernel
-# package name, too)
-current="$(uname -r | cut -f1,2 -d-)"
-# List versions of kernels that have reserve dependencies
-LatestVersions="$(dpkg-query -W -f='${Package} ${Status}\n' |
- awk '/^linux-image-(generic|lowlatency|virtual)(-lts-[^ ]+|) install ok installed/{print $1}' |
- xargs dpkg-query -W -f='${Depends}\n' |
- sed -nr "s/.*linux-image-([[:digit:].]+-[^-]+)-.*/\1/p" | sort -uV)"
+VersionsToPurge=""
+if [ "${CandidateVersionsToPurge}" ]; then
+# Do not include versions that are present in ${Versions}, in case both
+# -generic and -lowlatency kenrels are installed, but only the other is
+# marked for removal.
+ VersionsToPurge="$(comm -23 <(echo -e "${CandidateVersionsToPurge}") \
+  <(echo -e "${Versions}"))"
+fi
 
-# keep n versions that are older than the current one (if they exist).
-num=$(awk '($0==c){a=NR-1-n; if(a>0){print a}else{print 0} exit}' c=${current} n=$n <<<"${Versions}")
+if [ "${Versions}" ]; then
 
-# Get the older versions to remove; never remove latest kernels though.
-VersionsToPurge="$(comm -23 <(head -n ${num} <<<"${Versions}") <(echo -e "${LatestVersions}"))"
+ # keep n versions that are older than the current one (if they exist).
+ num=$(awk '($0==c){a=NR-1-n; if(a>0){print a}else{print 0} exit}' \
+ c=$(uname -r | cut -f1,2 -d-) n=$n <<<"${Versions}")
+
+ if (("${num}" > 0)); then
+
+    # List versions of kernels that have reserve dependencies
+
+    LatestVersions="$(dpkg-query -W -f='${Package} ${Status}\n' |
+    awk '/^linux-(.+-|)image-[^0-9]+(-lts-[^ ]+|) (install|hold) ok installed/{print $1}' |
+    xargs dpkg-query -W -f='${Depends}\n' |
+    sed -nr "s/\<linux-(.+-|)image-([0-9.]+-[^-]+)-.*/\2/p" | sort -uV)"
+
+    # Get the older versions to remove; never remove latest kernels though.
+    CandidateVersionsToPurge="$(comm -23 <(head -n ${num} <<<"${Versions}") \
+     <(echo -e "${LatestVersions}"))"
+
+    if [ "${CandidateVersionsToPurge}" ] ; then
+
+        for version in ${CandidateVersionsToPurge}; do
+         if ! dpkg-query -W -f='${Status}\n' "linux-image-${version}-*" |
+          grep -q '^hold'; then
+           # purge version, if it is not marked as held by e.g. apt-get hold
+           if [ "${VersionsToPurge}" ]; then
+            VersionsToPurge+=$'\n'"${version}"
+           else
+            VersionsToPurge="${version}"
+           fi
+         fi
+        done
+    fi
+ fi
+fi
 
 if [ "${VersionsToPurge}" ]; then
     # purge linux packages matching the versions
     apt-get -q ${simulate} ${yes} purge --auto-remove $(
-    sed -r -e 's/\./\\./g' -e 's/.*/^linux-.+-&($|-)/' <<<"$VersionsToPurge")
+    sed -r -e 's/\./\\./g' -e 's/.*/^linux-.+-&($|-)/' <<<"${VersionsToPurge}")
 else
     echo "0 kernels purged."
 fi
